### ISSUE TITLE
Board Question

### ISSUE THREAD

**Issue by nanospearing** [CasualCodersProjects/DS4-Type-C#8]
Sorry if this is a dumb question but, which Board is considered the best for playing with USB and charging?

**Comment by 12ian3** [comment]
Hi there,

I don't understand your question. Would you be able to rephrase it for me?

Thanks!

Aug 11, 2022 15:23:17 KozmikNano ***@***.***>:

**Comment by nanospearing** [comment]
Out of the list of boards that works for this project, which one is the best? Are they all the same?

**Comment by 12ian3** [comment]
Each board is unique to a specific controller. They are all the same general schematic, however certain shapes and pinouts are different. Otherwise, they all work the same.

You'll have to open your controller and figure out which of the 5 different models of boards your controller uses, then fab the correct replacement.

**Comment by nanospearing** [comment]
Ok, thanks!
